### PR TITLE
[ lint ] correct return type in error.c

### PR DESCRIPTION
**Pull request by stefan-hoeck**

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Looks like there is an issue with `struct itimerspec`. This should be POSIX conformant but seems to be unknow to macOS. @mattpolzin can you confirm that this does not work on MacOS?

**Comment by mattpolzin** [comment]
As best I can tell, `itimerspec` is indeed not defined anywhere in the Darwin libc headers. I thought Darwin was fully POSIX compliant but it turns out the actual docs say that the FreeBSD kernel it is based upon contains "Many of the POSIX APIs."

**Comment by stefan-hoeck** [comment]
Thanks for verifying this. Do you know if there is a CPP flag we can use to hide the few bits where Darwin is not POSIX compliant?

**Comment by mattpolzin** [comment]
I haven't found exactly what you were hoping for, but I did find something that seems to at least expose one thing that may not be POSIX compliant (at least for a particular POSIX version that I see referenced online in a few places).

```
CFLAGS='-std=c99 -D_POSIX_C_SOURCE=200809L'
```

**Comment by mattpolzin** [comment]
ok, it's surprisingly hard to find information on POSIX compliance but as of 2023 the latest versions of macOS are indeed certified as POSIX compliant but specifically to IEEE 1003.1-2001. That POSIX_C_SOURCE macro I mentioned in my previous comment can be set to `200112L` (per https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html#index-_005fPOSIX_005fC_005fSOURCE) in order to restrict the GCC compiler to that POSIX standard.

I'm not sure how perfect of a solution this is, though. It may well produce errors for missing symbols that darwin actually _does_ have (for example) because darwin may implement portions of later POSIX standards.

**Comment by stefan-hoeck** [comment]
So, I put the stuff in the *posix* lib that's not supported on Darwin behind a CPP flag. The functions are still in the Idris sources, but they won't be usable during codegen. As an alternative, we could use the same CPP flag and return some kind of non-supported error instead. I prefer the current solution.

I also turned of checking of the *linux* support files on Darwin, because those deal with utilities only available on Linux.

**Comment by mattpolzin** [comment]
Makes sense to me

**Comment by stefan-hoeck** [comment]
Thanks again for your help with this!

**Pull request merged**
